//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Data.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tourist.Data.Shared.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error this cell can&apos;t be empty..
        /// </summary>
        internal static string ErrorCellEmpty {
            get {
                return ResourceManager.GetString("ErrorCellEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the email field isn&apos;t valid..
        /// </summary>
        internal static string ErrorEmailNotValid {
            get {
                return ResourceManager.GetString("ErrorEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field has only 9 digits..
        /// </summary>
        internal static string ErrorNifNineDigits {
            get {
                return ResourceManager.GetString("ErrorNifNineDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field has only digits..
        /// </summary>
        internal static string ErrorNifOnlyDigits {
            get {
                return ResourceManager.GetString("ErrorNifOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the phone field has only digits..
        /// </summary>
        internal static string ErrorPhoneOnlyDigits {
            get {
                return ResourceManager.GetString("ErrorPhoneOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error string is not in the proper format..
        /// </summary>
        internal static string IsNotDateFormat {
            get {
                return ResourceManager.GetString("IsNotDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error can´t convert string to double..
        /// </summary>
        internal static string IsNotDouble {
            get {
                return ResourceManager.GetString("IsNotDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error can´t convert string to Enum..
        /// </summary>
        internal static string IsNotEnum {
            get {
                return ResourceManager.GetString("IsNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error can´t convert string to int..
        /// </summary>
        internal static string IsNotInteger {
            get {
                return ResourceManager.GetString("IsNotInteger", resourceCulture);
            }
        }
    }
}
