//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Client.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tourist.Client.Resources.Text.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Empty or Not complete!!!.
        /// </summary>
        internal static string DataEmptyOrNotComplete {
            get {
                return ResourceManager.GetString("DataEmptyOrNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the address field can&apos;t be empty..
        /// </summary>
        internal static string ErrorAddressEmpty {
            get {
                return ResourceManager.GetString("ErrorAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the email field can&apos;t be empty..
        /// </summary>
        internal static string ErrorEmailEmpty {
            get {
                return ResourceManager.GetString("ErrorEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the email field isn&apos;t valid..
        /// </summary>
        internal static string ErrorEmailNotValid {
            get {
                return ResourceManager.GetString("ErrorEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the name field can&apos;t be empty..
        /// </summary>
        internal static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field can&apos;t be empty..
        /// </summary>
        internal static string ErrorNIfEmpty {
            get {
                return ResourceManager.GetString("ErrorNIfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field has only 9 digits..
        /// </summary>
        internal static string ErrorNifNineDigits {
            get {
                return ResourceManager.GetString("ErrorNifNineDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field has only digits..
        /// </summary>
        internal static string ErrorNifOnlyDigits {
            get {
                return ResourceManager.GetString("ErrorNifOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the phone field can&apos;t be empty..
        /// </summary>
        internal static string ErrorPhoneEmpty {
            get {
                return ResourceManager.GetString("ErrorPhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the phone field has only digits..
        /// </summary>
        internal static string ErrorPhoneOnlyDigits {
            get {
                return ResourceManager.GetString("ErrorPhoneOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Button Pressed.
        /// </summary>
        internal static string ExitMessageTitle {
            get {
                return ResourceManager.GetString("ExitMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert all required fields to proceed..
        /// </summary>
        internal static string InformationDataNotComplete {
            get {
                return ResourceManager.GetString("InformationDataNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Information saved with Sucess !!!.
        /// </summary>
        internal static string InformationSaved {
            get {
                return ResourceManager.GetString("InformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error !!!.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username or password..
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sucessfull !!!.
        /// </summary>
        internal static string LoginSucessfull {
            get {
                return ResourceManager.GetString("LoginSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome  .
        /// </summary>
        internal static string LoginSucessfullMessage {
            get {
                return ResourceManager.GetString("LoginSucessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG|*.png|JPEG|*.jpg;*.jpeg.
        /// </summary>
        internal static string LogoFilter {
            get {
                return ResourceManager.GetString("LogoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Sucessfull.
        /// </summary>
        internal static string OperationSucessfull {
            get {
                return ResourceManager.GetString("OperationSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the password field can&apos;t be empty..
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Entity Logo.
        /// </summary>
        internal static string SaveLogoTitle {
            get {
                return ResourceManager.GetString("SaveLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the username field can&apos;t be empty..
        /// </summary>
        internal static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
    }
}
