//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourist.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tourist.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ActivityString {
            get {
                return ResourceManager.GetString("ActivityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AddressEdited With Sucess !!!.
        /// </summary>
        internal static string AddressEdited {
            get {
                return ResourceManager.GetString("AddressEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Added With Sucess !!!.
        /// </summary>
        internal static string AddString {
            get {
                return ResourceManager.GetString("AddString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BarGraph {
            get {
                object obj = ResourceManager.GetObject("BarGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  BithDate Edited With Sucess !!!.
        /// </summary>
        internal static string BirthDateEdited {
            get {
                return ResourceManager.GetString("BirthDateEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clients {
            get {
                object obj = ResourceManager.GetObject("clients", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Client.
        /// </summary>
        internal static string ClientString {
            get {
                return ResourceManager.GetString("ClientString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClosedLock {
            get {
                object obj = ResourceManager.GetObject("ClosedLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComingSoon {
            get {
                object obj = ResourceManager.GetObject("ComingSoon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a complete row before going to next Screen..
        /// </summary>
        internal static string CompleteRow {
            get {
                return ResourceManager.GetString("CompleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Empty or Not complete .
        /// </summary>
        internal static string CompleteRowTitle {
            get {
                return ResourceManager.GetString("CompleteRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Empty or Not complete!!!.
        /// </summary>
        internal static string DataEmptyOrNotComplete {
            get {
                return ResourceManager.GetString("DataEmptyOrNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Description Edited WIth Sucess !!!.
        /// </summary>
        internal static string DescriptionEdited {
            get {
                return ResourceManager.GetString("DescriptionEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Disponibility {
            get {
                object obj = ResourceManager.GetObject("Disponibility", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Email Edited With Sucess !!!.
        /// </summary>
        internal static string EmailEdited {
            get {
                return ResourceManager.GetString("EmailEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employees registered. .
        /// </summary>
        internal static string EmployeesListEmpty {
            get {
                return ResourceManager.GetString("EmployeesListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no employees registered. Please contact a manager to register a employer to proceed..
        /// </summary>
        internal static string EmployeesListEmptyMessage {
            get {
                return ResourceManager.GetString("EmployeesListEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employers {
            get {
                object obj = ResourceManager.GetObject("employers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        internal static string EmployerString {
            get {
                return ResourceManager.GetString("EmployerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Entity {
            get {
                object obj = ResourceManager.GetObject("Entity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the address field can&apos;t be empty..
        /// </summary>
        internal static string ErrorAddressEmpty {
            get {
                return ResourceManager.GetString("ErrorAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the email field can&apos;t be empty..
        /// </summary>
        internal static string ErrorEmailEmpty {
            get {
                return ResourceManager.GetString("ErrorEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the email field isn&apos;t valid..
        /// </summary>
        internal static string ErrorEmailNotValid {
            get {
                return ResourceManager.GetString("ErrorEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the name field can&apos;t be empty..
        /// </summary>
        internal static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field can&apos;t be empty..
        /// </summary>
        internal static string ErrorNIfEmpty {
            get {
                return ResourceManager.GetString("ErrorNIfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field has only 9 digits..
        /// </summary>
        internal static string ErrorNifNineDigits {
            get {
                return ResourceManager.GetString("ErrorNifNineDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the nif field has only digits..
        /// </summary>
        internal static string ErrorNifOnlyDigits {
            get {
                return ResourceManager.GetString("ErrorNifOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the phone field can&apos;t be empty..
        /// </summary>
        internal static string ErrorPhoneEmpty {
            get {
                return ResourceManager.GetString("ErrorPhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the phone field has only digits..
        /// </summary>
        internal static string ErrorPhoneOnlyDigits {
            get {
                return ResourceManager.GetString("ErrorPhoneOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Button Pressed !!!.
        /// </summary>
        internal static string ExitMessageTitle {
            get {
                return ResourceManager.GetString("ExitMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  First Name Edited With Sucess !!!.
        /// </summary>
        internal static string FirstNameEdited {
            get {
                return ResourceManager.GetString("FirstNameEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gender Edited With Sucess !!!.
        /// </summary>
        internal static string GenderEdited {
            get {
                return ResourceManager.GetString("GenderEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert all required fields to proceed..
        /// </summary>
        internal static string InformationDataNotComplete {
            get {
                return ResourceManager.GetString("InformationDataNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Information saved with Sucess !!!.
        /// </summary>
        internal static string InformationSaved {
            get {
                return ResourceManager.GetString("InformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Last Name Edited With Sucess !!!.
        /// </summary>
        internal static string LastNameEdited {
            get {
                return ResourceManager.GetString("LastNameEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error !!!.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your username or password..
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginFrame {
            get {
                object obj = ResourceManager.GetObject("LoginFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Sucessfull !!!.
        /// </summary>
        internal static string LoginSucessfull {
            get {
                return ResourceManager.GetString("LoginSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome  .
        /// </summary>
        internal static string LoginSucessfullMessage {
            get {
                return ResourceManager.GetString("LoginSucessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG|*.png|JPEG|*.jpg;*.jpeg.
        /// </summary>
        internal static string LogoFilter {
            get {
                return ResourceManager.GetString("LogoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoFrame {
            get {
                object obj = ResourceManager.GetObject("LogoFrame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magnifier {
            get {
                object obj = ResourceManager.GetObject("Magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Managers {
            get {
                object obj = ResourceManager.GetObject("Managers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string ManagerString {
            get {
                return ResourceManager.GetString("ManagerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Message {
            get {
                object obj = ResourceManager.GetObject("Message", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nationality Edited With Sucess !!!.
        /// </summary>
        internal static string NationalityEdited {
            get {
                return ResourceManager.GetString("NationalityEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nif Edited With Sucess !!!.
        /// </summary>
        internal static string NifEdited {
            get {
                return ResourceManager.GetString("NifEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Sucessfull.
        /// </summary>
        internal static string OperationSucessfull {
            get {
                return ResourceManager.GetString("OperationSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Password Edited With Sucess !!!.
        /// </summary>
        internal static string PasswordEdited {
            get {
                return ResourceManager.GetString("PasswordEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the password field can&apos;t be empty..
        /// </summary>
        internal static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Phone Edited With Sucess !!!.
        /// </summary>
        internal static string PhoneEdited {
            get {
                return ResourceManager.GetString("PhoneEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerOff {
            get {
                object obj = ResourceManager.GetObject("PowerOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap preferences {
            get {
                object obj = ResourceManager.GetObject("preferences", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the row selected ?.
        /// </summary>
        internal static string RemoveString {
            get {
                return ResourceManager.GetString("RemoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Operation .
        /// </summary>
        internal static string RemoveTitle {
            get {
                return ResourceManager.GetString("RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string RoomString {
            get {
                return ResourceManager.GetString("RoomString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Entity Logo.
        /// </summary>
        internal static string SaveLogoTitle {
            get {
                return ResourceManager.GetString("SaveLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap services {
            get {
                object obj = ResourceManager.GetObject("services", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  State Edited With Sucess !!!.
        /// </summary>
        internal static string StateEditedString {
            get {
                return ResourceManager.GetString("StateEditedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string TransportString {
            get {
                return ResourceManager.GetString("TransportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Type Edited With Sucess !!!.
        /// </summary>
        internal static string TypeEditedString {
            get {
                return ResourceManager.GetString("TypeEditedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Username Edited With Sucess !!!.
        /// </summary>
        internal static string UsernameEdited {
            get {
                return ResourceManager.GetString("UsernameEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error the username field can&apos;t be empty..
        /// </summary>
        internal static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        internal static string WelcomeString {
            get {
                return ResourceManager.GetString("WelcomeString", resourceCulture);
            }
        }
    }
}
